// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// PASSWORD RESET
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";


export const AUTH_IN_PROGRESS = 'AUTH_IN_PROGRESS';
export const AUTH_ERROR_MESSAGE = 'AUTH_ERROR_MESSAGE';


export const LABELS_RECEIVED = 'LABELS_RECEIVED';

export const NOTES_RECEIVED = 'NOTES_RECEIVED';
export const EMPTY_NOTES = 'EMPTY_NOTES';